#
# production configuration
#
spring:
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 100MB
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://49.247.9.194:8761/eureka
storage:
   location: /service-storage/assets
   httpd:
      host: 49.247.9.194
      port: 9999
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      me:
         kickscar:
            msa:
               service:
                  storage:
                     exception: ERROR